application: xiaomiavail
version: 1
runtime: go
api_version: go1

default_expiration: "4d"

handlers:
- url: /google198f15972d7d87d0.html
  static_files: googleVerification/google198f15972d7d87d0.html
  upload: googleVerification/google198f15972d7d87d0.html

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts
  
- url: /.*
  script: _go_app